root = "."
testdata_dir = "testdata"
tmp_dir = ".air"

[build]
  args_bin = []
  bin = "./bin/gotemplate"
  cmd = "go build -o ./bin/gotemplate ./cmd/api"
  delay = 1000
  exclude_dir = [
    ".agents",
    ".air",
    ".zed",
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "bin",
    "build",
    "scripts",
    "api",
  ]
  exclude_file = []
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_file = []
  include_ext = ["go", "env"]
  kill_delay = "0s"
  log = "build.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = "magenta"
  build = "yellow"
  main = "cyan"
  runner = "green"
  watcher = "white"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false
  disable_spinner = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[watch]
  ignore-dir = []
  ignore-file = []
  ignore-file_config = ""
  paths = []
  paths_config = ""

[trigger]
  delay = 0
  interrupt = true
